# Generated by Django 4.2.3 on 2023-10-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_views_routing_homework', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'get_latest_by': 'created_at', 'ordering': ['-created_at']},
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(check=models.Q(('full_name__gte', 5)), name='full_name_gte_5'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users_info',
        ),
    ]
