# Generated by Django 4.2.3 on 2023-10-04 22:11

from django.db import migrations, models
import django_views_routing_homework.validators


class Migration(migrations.Migration):

    dependencies = [
        ('django_views_routing_homework', '0002_alter_user_options_user_full_name_gte_5_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='full_name_gte_5',
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=256, validators=[django_views_routing_homework.validators.validate_min_length_full_name]),
        ),
        migrations.AlterField(
            model_name='user',
            name='registered_from',
            field=models.CharField(choices=[('wb', 'website'), ('ma', 'mobile_app')], default='wb', max_length=2),
        ),
    ]
